<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CategoryBrandVariantBaseSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedCategories();
        $this->seedBrands();
        $this->seedVariantTypes();
        $this->seedVariantOptions();
    }

    protected function seedCategories(): void
    {
        DB::table('categories')->insert([
            [
                'id' => 1,
                'title' => "Men's Fashion",
                'slug' => 'mens-fashion',
                'summary' => "Men's clothing and accessories",
                'photo' => 'categories/mens-fashion.webp',
                'parent_id' => null,
                'level' => 0,
                'path' => '1',
                'sort_order' => 1,
                'has_children' => true,
                'children_count' => 4,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => true,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'title' => "Women's Fashion",
                'slug' => 'womens-fashion',
                'summary' => "Women's clothing and accessories",
                'photo' => 'categories/womens-fashion.webp',
                'parent_id' => null,
                'level' => 0,
                'path' => '2',
                'sort_order' => 2,
                'has_children' => true,
                'children_count' => 4,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => true,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'title' => "Kids Fashion",
                'slug' => 'kids-fashion',
                'summary' => "Kids clothing and accessories",
                'photo' => 'categories/kids-fashion.webp',
                'parent_id' => null,
                'level' => 0,
                'path' => '3',
                'sort_order' => 3,
                'has_children' => true,
                'children_count' => 4,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'title' => 'Electronics',
                'slug' => 'electronics',
                'summary' => 'Electronic devices and gadgets',
                'photo' => 'categories/electronics.webp',
                'parent_id' => null,
                'level' => 0,
                'path' => '4',
                'sort_order' => 4,
                'has_children' => true,
                'children_count' => 3,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => true,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Men's subcategories
            [
                'id' => 5,
                'title' => "Men's Shirts",
                'slug' => 'mens-shirts',
                'summary' => null,
                'photo' => null,
                'parent_id' => 1,
                'level' => 1,
                'path' => '1/5',
                'sort_order' => 1,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'title' => "Men's Jeans",
                'slug' => 'mens-jeans',
                'summary' => null,
                'photo' => null,
                'parent_id' => 1,
                'level' => 1,
                'path' => '1/6',
                'sort_order' => 2,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'title' => "Men's Jackets",
                'slug' => 'mens-jackets',
                'summary' => null,
                'photo' => null,
                'parent_id' => 1,
                'level' => 1,
                'path' => '1/7',
                'sort_order' => 3,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'title' => "Men's Shoes",
                'slug' => 'mens-shoes',
                'summary' => null,
                'photo' => null,
                'parent_id' => 1,
                'level' => 1,
                'path' => '1/8',
                'sort_order' => 4,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Women's subcategories
            [
                'id' => 9,
                'title' => "Women's Dresses",
                'slug' => 'womens-dresses',
                'summary' => null,
                'photo' => null,
                'parent_id' => 2,
                'level' => 1,
                'path' => '2/9',
                'sort_order' => 1,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'title' => "Women's Tops",
                'slug' => 'womens-tops',
                'summary' => null,
                'photo' => null,
                'parent_id' => 2,
                'level' => 1,
                'path' => '2/10',
                'sort_order' => 2,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'title' => "Women's Jeans",
                'slug' => 'womens-jeans',
                'summary' => null,
                'photo' => null,
                'parent_id' => 2,
                'level' => 1,
                'path' => '2/11',
                'sort_order' => 3,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'title' => "Women's Shoes",
                'slug' => 'womens-shoes',
                'summary' => null,
                'photo' => null,
                'parent_id' => 2,
                'level' => 1,
                'path' => '2/12',
                'sort_order' => 4,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Kids subcategories
            [
                'id' => 13,
                'title' => 'Boys Clothing',
                'slug' => 'boys-clothing',
                'summary' => null,
                'photo' => null,
                'parent_id' => 3,
                'level' => 1,
                'path' => '3/13',
                'sort_order' => 1,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'title' => 'Girls Clothing',
                'slug' => 'girls-clothing',
                'summary' => null,
                'photo' => null,
                'parent_id' => 3,
                'level' => 1,
                'path' => '3/14',
                'sort_order' => 2,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'title' => 'Kids Shoes',
                'slug' => 'kids-shoes',
                'summary' => null,
                'photo' => null,
                'parent_id' => 3,
                'level' => 1,
                'path' => '3/15',
                'sort_order' => 3,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'title' => 'Kids Accessories',
                'slug' => 'kids-accessories',
                'summary' => null,
                'photo' => null,
                'parent_id' => 3,
                'level' => 1,
                'path' => '3/16',
                'sort_order' => 4,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Electronics subcategories
            [
                'id' => 17,
                'title' => 'Smartphones',
                'slug' => 'smartphones',
                'summary' => null,
                'photo' => null,
                'parent_id' => 4,
                'level' => 1,
                'path' => '4/17',
                'sort_order' => 1,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'title' => 'Laptops',
                'slug' => 'laptops',
                'summary' => null,
                'photo' => null,
                'parent_id' => 4,
                'level' => 1,
                'path' => '4/18',
                'sort_order' => 2,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'title' => 'Headphones',
                'slug' => 'headphones',
                'summary' => null,
                'photo' => null,
                'parent_id' => 4,
                'level' => 1,
                'path' => '4/19',
                'sort_order' => 3,
                'has_children' => false,
                'children_count' => 0,
                'products_count' => 0,
                'status' => 'active',
                'is_featured' => false,
                'added_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::statement("SELECT setval(pg_get_serial_sequence('categories', 'id'), COALESCE((SELECT MAX(id) FROM categories), 0))");
    }

    protected function seedBrands(): void
    {
        $brands = [
            ['title' => 'Nike', 'slug' => 'nike', 'status' => 'active'],
            ['title' => 'Adidas', 'slug' => 'adidas', 'status' => 'active'],
            ['title' => 'Puma', 'slug' => 'puma', 'status' => 'active'],
            ['title' => 'Zara', 'slug' => 'zara', 'status' => 'active'],
            ['title' => 'H&M', 'slug' => 'hm', 'status' => 'active'],
            ['title' => 'Samsung', 'slug' => 'samsung', 'status' => 'active'],
            ['title' => 'Apple', 'slug' => 'apple', 'status' => 'active'],
            ['title' => 'Sony', 'slug' => 'sony', 'status' => 'active'],
            ['title' => 'Dell', 'slug' => 'dell', 'status' => 'active'],
            ['title' => 'HP', 'slug' => 'hp', 'status' => 'active'],
        ];

        foreach ($brands as $brand) {
            DB::table('brands')->insert([
                'title' => $brand['title'],
                'slug' => $brand['slug'],
                'status' => $brand['status'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        DB::statement("SELECT setval(pg_get_serial_sequence('brands', 'id'), COALESCE((SELECT MAX(id) FROM brands), 0))");
    }

    protected function seedVariantTypes(): void
    {
        DB::table('product_variant_types')->insert([
            [
                'id' => 1,
                'name' => 'color',
                'display_name' => 'Color',
                'sort_order' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'size',
                'display_name' => 'Size',
                'sort_order' => 2,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'storage',
                'display_name' => 'Storage',
                'sort_order' => 3,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'ram',
                'display_name' => 'RAM',
                'sort_order' => 4,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::statement("SELECT setval(pg_get_serial_sequence('product_variant_types', 'id'), COALESCE((SELECT MAX(id) FROM product_variant_types), 0))");
    }

    protected function seedVariantOptions(): void
    {
        $options = [
            // Colors (type_id = 1)
            ['variant_type_id' => 1, 'value' => 'red', 'display_value' => 'Red', 'hex_color' => '#FF0000', 'sort_order' => 1, 'status' => 'active'],
            ['variant_type_id' => 1, 'value' => 'blue', 'display_value' => 'Blue', 'hex_color' => '#0000FF', 'sort_order' => 2, 'status' => 'active'],
            ['variant_type_id' => 1, 'value' => 'green', 'display_value' => 'Green', 'hex_color' => '#00FF00', 'sort_order' => 3, 'status' => 'active'],
            ['variant_type_id' => 1, 'value' => 'black', 'display_value' => 'Black', 'hex_color' => '#000000', 'sort_order' => 4, 'status' => 'active'],
            ['variant_type_id' => 1, 'value' => 'white', 'display_value' => 'White', 'hex_color' => '#FFFFFF', 'sort_order' => 5, 'status' => 'active'],
            ['variant_type_id' => 1, 'value' => 'yellow', 'display_value' => 'Yellow', 'hex_color' => '#FFFF00', 'sort_order' => 6, 'status' => 'active'],
            ['variant_type_id' => 1, 'value' => 'orange', 'display_value' => 'Orange', 'hex_color' => '#FFA500', 'sort_order' => 7, 'status' => 'active'],
            ['variant_type_id' => 1, 'value' => 'purple', 'display_value' => 'Purple', 'hex_color' => '#800080', 'sort_order' => 8, 'status' => 'active'],

            // Sizes (type_id = 2)
            ['variant_type_id' => 2, 'value' => 'xs', 'display_value' => 'XS', 'hex_color' => null, 'sort_order' => 1, 'status' => 'active'],
            ['variant_type_id' => 2, 'value' => 's', 'display_value' => 'S', 'hex_color' => null, 'sort_order' => 2, 'status' => 'active'],
            ['variant_type_id' => 2, 'value' => 'm', 'display_value' => 'M', 'hex_color' => null, 'sort_order' => 3, 'status' => 'active'],
            ['variant_type_id' => 2, 'value' => 'l', 'display_value' => 'L', 'hex_color' => null, 'sort_order' => 4, 'status' => 'active'],
            ['variant_type_id' => 2, 'value' => 'xl', 'display_value' => 'XL', 'hex_color' => null, 'sort_order' => 5, 'status' => 'active'],
            ['variant_type_id' => 2, 'value' => 'xxl', 'display_value' => 'XXL', 'hex_color' => null, 'sort_order' => 6, 'status' => 'active'],

            // Storage (type_id = 3)
            ['variant_type_id' => 3, 'value' => '64gb', 'display_value' => '64GB', 'hex_color' => null, 'sort_order' => 1, 'status' => 'active'],
            ['variant_type_id' => 3, 'value' => '128gb', 'display_value' => '128GB', 'hex_color' => null, 'sort_order' => 2, 'status' => 'active'],
            ['variant_type_id' => 3, 'value' => '256gb', 'display_value' => '256GB', 'hex_color' => null, 'sort_order' => 3, 'status' => 'active'],
            ['variant_type_id' => 3, 'value' => '512gb', 'display_value' => '512GB', 'hex_color' => null, 'sort_order' => 4, 'status' => 'active'],
            ['variant_type_id' => 3, 'value' => '1tb', 'display_value' => '1TB', 'hex_color' => null, 'sort_order' => 5, 'status' => 'active'],

            // RAM (type_id = 4)
            ['variant_type_id' => 4, 'value' => '4gb', 'display_value' => '4GB', 'hex_color' => null, 'sort_order' => 1, 'status' => 'active'],
            ['variant_type_id' => 4, 'value' => '8gb', 'display_value' => '8GB', 'hex_color' => null, 'sort_order' => 2, 'status' => 'active'],
            ['variant_type_id' => 4, 'value' => '16gb', 'display_value' => '16GB', 'hex_color' => null, 'sort_order' => 3, 'status' => 'active'],
            ['variant_type_id' => 4, 'value' => '32gb', 'display_value' => '32GB', 'hex_color' => null, 'sort_order' => 4, 'status' => 'active'],
        ];

        foreach ($options as $option) {
            DB::table('product_variant_options')->insert([
                'variant_type_id' => $option['variant_type_id'],
                'value' => $option['value'],
                'display_value' => $option['display_value'],
                'hex_color' => $option['hex_color'],
                'sort_order' => $option['sort_order'],
                'status' => $option['status'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        DB::statement("SELECT setval(pg_get_serial_sequence('product_variant_options', 'id'), COALESCE((SELECT MAX(id) FROM product_variant_options), 0))");
    }
}
